/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CheckoutRequest { 
    userId?: number;
    guestId?: string;
    guestName?: string;
    guestEmail?: string;
    guestPhone?: string;
    shippingAddress: string;
    shippingProvince?: string;
    shippingDistrict?: string;
    shippingWard?: string;
    shippingNote?: string;
    billingAddress?: string;
    billingProvince?: string;
    billingDistrict?: string;
    billingWard?: string;
    paymentMethod?: string;
    shippingMethod?: string;
}

