/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReturnItemRequest } from './returnItemRequest';


export interface CreateReturnRequest { 
    orderId?: number;
    returnType?: CreateReturnRequestReturnTypeEnum;
    reason?: string;
    description?: string;
    items?: Array<ReturnItemRequest>;
    imageUrls?: Array<string>;
    guestId?: string;
    guestPhone?: string;
    guestEmail?: string;
}
export enum CreateReturnRequestReturnTypeEnum {
    RETURN = 'RETURN',
    EXCHANGE = 'EXCHANGE',
    WARRANTY = 'WARRANTY'
};



