/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReturnItemResponse } from './returnItemResponse';


export interface ReturnResponse { 
    id?: number;
    orderId?: number;
    userId?: number;
    guestId?: string;
    returnType?: ReturnResponseReturnTypeEnum;
    reason?: string;
    description?: string;
    status?: ReturnResponseStatusEnum;
    refundAmount?: number;
    refundTransactionId?: string;
    adminNote?: string;
    returnTrackingCode?: string;
    requestDate?: string;
    processedDate?: string;
    completedDate?: string;
    items?: Array<ReturnItemResponse>;
    imageUrls?: Array<string>;
}
export enum ReturnResponseReturnTypeEnum {
    RETURN = 'RETURN',
    EXCHANGE = 'EXCHANGE',
    WARRANTY = 'WARRANTY'
};
export enum ReturnResponseStatusEnum {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED'
};



