/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReturnItemRequest { 
    orderItemId?: number;
    productId?: number;
    quantity?: number;
    reason?: string;
}

