export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './bannerController.service';
import { BannerControllerService } from './bannerController.service';
export * from './cartController.service';
import { CartControllerService } from './cartController.service';
export * from './categoryController.service';
import { CategoryControllerService } from './categoryController.service';
export * from './inventoryController.service';
import { InventoryControllerService } from './inventoryController.service';
export * from './mediaController.service';
import { MediaControllerService } from './mediaController.service';
export * from './notificationController.service';
import { NotificationControllerService } from './notificationController.service';
export * from './notificationSettingController.service';
import { NotificationSettingControllerService } from './notificationSettingController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './pageController.service';
import { PageControllerService } from './pageController.service';
export * from './paymentController.service';
import { PaymentControllerService } from './paymentController.service';
export * from './postController.service';
import { PostControllerService } from './postController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './shippingController.service';
import { ShippingControllerService } from './shippingController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthenticationControllerService, BannerControllerService, CartControllerService, CategoryControllerService, InventoryControllerService, MediaControllerService, NotificationControllerService, NotificationSettingControllerService, OrderControllerService, PageControllerService, PaymentControllerService, PostControllerService, ProductControllerService, ShippingControllerService, UserControllerService];
