export * from './accountController.service';
import { AccountControllerService } from './accountController.service';
export * from './categoryAdminController.service';
import { CategoryAdminControllerService } from './categoryAdminController.service';
export * from './inventoryAdminController.service';
import { InventoryAdminControllerService } from './inventoryAdminController.service';
export * from './orderAdminController.service';
import { OrderAdminControllerService } from './orderAdminController.service';
export * from './paymentAdminProxyController.service';
import { PaymentAdminProxyControllerService } from './paymentAdminProxyController.service';
export * from './productAdminController.service';
import { ProductAdminControllerService } from './productAdminController.service';
export * from './shippingAdminController.service';
import { ShippingAdminControllerService } from './shippingAdminController.service';
export const APIS = [AccountControllerService, CategoryAdminControllerService, InventoryAdminControllerService, OrderAdminControllerService, PaymentAdminProxyControllerService, ProductAdminControllerService, ShippingAdminControllerService];
