openapi: 3.1.0
info:
  title: Shop App API
  description: API documentation for Shop App
  version: v1
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/user/products:
    get:
      tags:
      - product-user-controller
      operationId: getAllProducts
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageProductResponse"
  /api/user/products/{id}:
    get:
      tags:
      - product-user-controller
      operationId: getProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductResponse"
components:
  schemas:
    ImageDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
    PageProductResponse:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: "#/components/schemas/ProductResponse"
        number:
          type: integer
          format: int32
        sort:
          $ref: "#/components/schemas/SortObject"
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        pageable:
          $ref: "#/components/schemas/PageableObject"
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: "#/components/schemas/SortObject"
        paged:
          type: boolean
        pageSize:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
        unpaged:
          type: boolean
    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sku:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        importPrice:
          type: number
        categoryId:
          type: integer
          format: int64
        categoryName:
          type: string
        images:
          type: array
          items:
            $ref: "#/components/schemas/ImageDTO"
        variants:
          type: array
          items:
            $ref: "#/components/schemas/VariantResponse"
    SortObject:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
    VariantResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sizeName:
          type: string
        color:
          type: string
        stock:
          type: integer
          format: int32
        reservedQuantity:
          type: integer
          format: int32
        availableQuantity:
          type: integer
          format: int32
        importPrice:
          type: number
        sellingPrice:
          type: number
