openapi: 3.1.0
info:
  title: Shop App API
  description: API documentation for Shop App
  version: v1
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/user/cart/update:
    put:
      tags:
      - cart-user-controller
      operationId: updateItem
      parameters:
      - name: userId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      - name: guestId
        in: query
        required: false
        schema:
          type: string
      - name: productId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: quantity
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CartResponse"
  /api/user/cart/merge:
    post:
      tags:
      - cart-user-controller
      operationId: mergeGuestCart
      parameters:
      - name: guestId
        in: query
        required: false
        schema:
          type: string
      - name: userId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CartResponse"
  /api/user/cart/add:
    post:
      tags:
      - cart-user-controller
      operationId: addItem
      parameters:
      - name: userId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      - name: guestId
        in: query
        required: false
        schema:
          type: string
      - name: productId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: quantity
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CartResponse"
  /api/user/products:
    get:
      tags:
      - product-user-controller
      operationId: getAllProducts
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageProductResponse"
  /api/user/products/{id}:
    get:
      tags:
      - product-user-controller
      operationId: getProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductResponse"
  /api/user/cart:
    get:
      tags:
      - cart-user-controller
      operationId: getCart
      parameters:
      - name: userId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      - name: guestId
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CartResponse"
  /api/user/cart/remove:
    delete:
      tags:
      - cart-user-controller
      operationId: removeItem
      parameters:
      - name: userId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      - name: guestId
        in: query
        required: false
        schema:
          type: string
      - name: productId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CartResponse"
components:
  schemas:
    CartItemResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        productName:
          type: string
        quantity:
          type: integer
          format: int32
        price:
          type: number
        images:
          type: array
          items:
            $ref: "#/components/schemas/ImageDTO"
    CartResponse:
      type: object
      properties:
        cartId:
          type: integer
          format: int64
        user:
          $ref: "#/components/schemas/UserResponse"
        guestId:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/CartItemResponse"
        totalPrice:
          type: number
    ImageDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
        roles:
          type: array
          items:
            type: string
        pushToken:
          type: string
    PageProductResponse:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: "#/components/schemas/ProductResponse"
        number:
          type: integer
          format: int32
        sort:
          $ref: "#/components/schemas/SortObject"
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        pageable:
          $ref: "#/components/schemas/PageableObject"
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: "#/components/schemas/SortObject"
        unpaged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        paged:
          type: boolean
        pageSize:
          type: integer
          format: int32
    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sku:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        importPrice:
          type: number
        categoryId:
          type: integer
          format: int64
        categoryName:
          type: string
        images:
          type: array
          items:
            $ref: "#/components/schemas/ImageDTO"
        colors:
          type: array
          items:
            type: string
        sizes:
          type: array
          items:
            type: string
        variants:
          type: array
          items:
            $ref: "#/components/schemas/VariantResponse"
    SortObject:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
    VariantResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sizeName:
          type: string
        color:
          type: string
        stock:
          type: integer
          format: int32
        reservedQuantity:
          type: integer
          format: int32
        availableQuantity:
          type: integer
          format: int32
        importPrice:
          type: number
        sellingPrice:
          type: number
        thumbnail:
          type: string
