export * from './accUserController.service';
import { AccUserControllerService } from './accUserController.service';
export * from './cartProxyController.service';
import { CartProxyControllerService } from './cartProxyController.service';
export * from './locationController.service';
import { LocationControllerService } from './locationController.service';
export * from './orderProxyController.service';
import { OrderProxyControllerService } from './orderProxyController.service';
export * from './paymentProxyController.service';
import { PaymentProxyControllerService } from './paymentProxyController.service';
export * from './productUserController.service';
import { ProductUserControllerService } from './productUserController.service';
export * from './shippingUserController.service';
import { ShippingUserControllerService } from './shippingUserController.service';
export const APIS = [AccUserControllerService, CartProxyControllerService, LocationControllerService, OrderProxyControllerService, PaymentProxyControllerService, ProductUserControllerService, ShippingUserControllerService];
