/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BannerResponse { 
    id?: number;
    imageUrl?: string;
    link?: string;
    position?: string;
    sortOrder?: number;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
}

