/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponse } from './userResponse';
import { CartItemResponse } from './cartItemResponse';


export interface CartResponse { 
    cartId?: number;
    user?: UserResponse;
    guestId?: string;
    items?: Array<CartItemResponse>;
}

