/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemRequest } from './orderItemRequest';


export interface CreateOrderRequest { 
    userId?: number;
    guestName?: string;
    guestEmail?: string;
    guestPhone?: string;
    shippingAddress?: string;
    billingAddress?: string;
    items: Array<OrderItemRequest>;
}

