/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationRequest { 
    receiverId?: number;
    title?: string;
    message?: string;
    channel?: NotificationRequest.ChannelEnum;
    broadcast?: boolean;
}
export namespace NotificationRequest {
    export const ChannelEnum = {
        Email: 'EMAIL',
        Sms: 'SMS',
        Push: 'PUSH'
    } as const;
    export type ChannelEnum = typeof ChannelEnum[keyof typeof ChannelEnum];
}


