/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationResponse { 
    id?: number;
    receiverId?: number;
    title?: string;
    message?: string;
    readFlag?: boolean;
    status?: string;
    channel?: string;
    broadcast?: boolean;
    messageCount?: number;
    createdAt?: string;
}

