/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';


export interface OrderItem { 
    id?: number;
    productId?: number;
    productName?: string;
    price?: number;
    quantity?: number;
    order?: Order;
}

