/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PageResponse { 
    id?: number;
    slug?: string;
    title?: string;
    summary?: string;
    content?: string;
    metaTitle?: string;
    metaDescription?: string;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
}

