/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostResponse { 
    id?: number;
    title?: string;
    slug?: string;
    summary?: string;
    content?: string;
    categoryId?: number;
    author?: string;
    active?: boolean;
    publishedAt?: string;
    createdAt?: string;
    updatedAt?: string;
}

