/**
 * Shop App API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface User { 
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    username?: string;
    password?: string;
    email?: string;
    phone?: string;
    address?: string;
    roles?: Set<Role>;
    pushToken?: string;
}

