/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemEntity } from './orderItemEntity';


export interface OrderEntity { 
    createdAt?: string;
    updatedAt?: string;
    id?: number;
    userId?: number;
    guestName?: string;
    guestEmail?: string;
    guestPhone?: string;
    shippingAddress?: string;
    billingAddress?: string;
    items?: Array<OrderItemEntity>;
    totalPrice?: number;
    status?: OrderEntity.StatusEnum;
    paymentStatus?: OrderEntity.PaymentStatusEnum;
}
export namespace OrderEntity {
    export const StatusEnum = {
        New: 'NEW',
        Confirmed: 'CONFIRMED',
        Processing: 'PROCESSING',
        Completed: 'COMPLETED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const PaymentStatusEnum = {
        Pending: 'PENDING',
        Paid: 'PAID',
        Failed: 'FAILED'
    } as const;
    export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];
}


