/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderEntity } from './orderEntity';


export interface OrderItemEntity { 
    createdAt?: string;
    updatedAt?: string;
    id?: number;
    productId?: number;
    productName?: string;
    price?: number;
    quantity?: number;
    order?: OrderEntity;
}

