/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReturnResponse } from './returnResponse';


export interface PageResponseReturnResponse { 
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    data?: Array<ReturnResponse>;
}

