/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShippingResponse } from './shippingResponse';


export interface PageShippingResponse { 
    content?: Array<ShippingResponse>;
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
    first?: boolean;
    last?: boolean;
}

