/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentSearchRequest { 
    status?: PaymentSearchRequestStatusEnum;
    method?: PaymentSearchRequestMethodEnum;
    fromDate?: string;
    toDate?: string;
    minAmount?: number;
    maxAmount?: number;
}
export enum PaymentSearchRequestStatusEnum {
    PENDING = 'PENDING',
    PAID = 'PAID',
    FAILED = 'FAILED',
    REFUNDED = 'REFUNDED',
    CANCELLED = 'CANCELLED'
};
export enum PaymentSearchRequestMethodEnum {
    CASH = 'CASH',
    ONLINE = 'ONLINE',
    MOMO = 'MOMO',
    PAYPAL = 'PAYPAL',
    CREDIT_CARD = 'CREDIT_CARD'
};



