/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentSummaryResponse { 
    totalAmount?: number;
    pendingAmount?: number;
    totalTransactions?: number;
    successfulTransactions?: number;
}

