/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VariantUpdateRequest } from './variantUpdateRequest';


export interface ProductUpdateRequest { 
    sku?: string;
    name?: string;
    description?: string;
    price?: number;
    importPrice?: number;
    categoryId?: number;
    images?: Array<string>;
    deletedImageIds?: Array<number>;
    variants?: Array<VariantUpdateRequest>;
}

