/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReturnItemResponse { 
    id?: number;
    productId?: number;
    productName?: string;
    quantity?: number;
    reason?: string;
    unitPrice?: number;
    subtotal?: number;
    images?: Array<string>;
}

