/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionEntity } from './permissionEntity';


export interface RoleEntity { 
    createdAt?: string;
    updatedAt?: string;
    name?: string;
    description?: string;
    permissions?: Set<PermissionEntity>;
}

