/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShippingResponse { 
    id?: number;
    orderId?: number;
    userId?: number;
    recipientName?: string;
    recipientPhone?: string;
    recipientEmail?: string;
    recipientAddress?: string;
    shippingCompany?: string;
    shippingMethod?: string;
    trackingNumber?: string;
    shippingFee?: number;
    estimatedDeliveryDays?: number;
    estimatedDeliveryDate?: string;
    status?: ShippingResponseStatusEnum;
    currentLocation?: string;
    notes?: string;
    shippedAt?: string;
    deliveredAt?: string;
    cancelledAt?: string;
    lastSyncAt?: string;
    createdAt?: string;
    updatedAt?: string;
}
export enum ShippingResponseStatusEnum {
    PREPARING = 'PREPARING',
    READY_TO_SHIP = 'READY_TO_SHIP',
    SHIPPED = 'SHIPPED',
    IN_TRANSIT = 'IN_TRANSIT',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    CANCELLED = 'CANCELLED',
    RETURNED = 'RETURNED',
    FAILED = 'FAILED'
};



