/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShippingUpdateRequest { 
    trackingCode?: string;
    shippingCompany?: string;
    shippingMethod?: string;
    shippingFee?: number;
    estimatedDeliveryDays?: number;
    notes?: string;
}

