/**
 * Shop Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductUpdateRequest } from './productUpdateRequest';
import { VariantUpdateRequest } from './variantUpdateRequest';


export interface UpdateProductRequest { 
    product: ProductUpdateRequest;
    files?: Array<Blob>;
    variants?: Array<VariantUpdateRequest>;
}

